version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: marketplace_database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  my_marketplace_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}

volumes:
  postgres_db:
    driver: local
